package application;

import java.net.URL;
import java.util.Random;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.stage.Stage;

public class MainMenu extends Application {

    private static MediaPlayer menuPlayer;
    private final Random random = new Random();
    
    // Create a static reference to the controller so our music engine can access it
    private static MainMenuController activeController;

    private final String[] playlist = {
        "Aylex - Successful (freetouse.com).wav",
        "Balynt - Other Side (freetouse.com).wav",
        "Danza Kuduro Remix - Don Omar ft. Daddy Yankee & Arcangel ° Letra - Sad Moon.wav",
        "IShowSpeed - World Cup (Champions) (Lyrics) - 7clouds.wav",
        "K'NAAN - Wavin' Flag World Cup Song - Arcade Music.wav", 
        "Live While Were Young .wav",
        "One Direction - Drag Me Down (Lyrics) - Lyrical Music Studio.wav",
        "Pufino - Arbiters Trial (freetouse.com).wav",
        "ravyn lenae - love me not [ slowed + reverb ] (lyrics) - slowed songs.wav",
        "The Beach Boys - Surfin' USA (Lyrics) BUGG Lyrics - BUGG Lyrics.wav"
    };

    @Override
    public void start(Stage primaryStage) {
        try {
            // Change this line to save the loader instance
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/application/MainMenu.fxml"));
            Parent root = loader.load();
            
            // Capture the controller instance automatically generated by FXML
            activeController = loader.getController();

            Scene scene = new Scene(root, 1200, 800);
            
            // --- THE FORCE FILL FIX ---
            javafx.scene.image.ImageView bg = (javafx.scene.image.ImageView) root.lookup("#menuBackgroundImg");
            if (bg != null) {
                bg.fitWidthProperty().bind(scene.widthProperty());
                bg.fitHeightProperty().bind(scene.heightProperty());
            }
            // ---------------------------

            scene.getStylesheets().add(getClass().getResource("/application/application.css").toExternalForm());
            
            primaryStage.setTitle("Baseball Game - Main Menu");
            primaryStage.setScene(scene);
            primaryStage.setResizable(true);
            primaryStage.show();
            
            // --- START PLAYLIST FLOW ---
            playNextRandomSong();
            
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    private void playNextRandomSong() {
        try {
            String selectedTrack = playlist[random.nextInt(playlist.length)];
            java.net.URL resource = getClass().getResource("/songs2/" + selectedTrack);
            
            if (resource == null) {
                System.out.println("Could not locate track: " + selectedTrack);
                return;
            }

            javafx.scene.media.Media media = new javafx.scene.media.Media(resource.toExternalForm());
            menuPlayer = new javafx.scene.media.MediaPlayer(media);
            menuPlayer.play();
            
            System.out.println("Jukebox successfully playing: " + selectedTrack);

            // Clean up the name for the UI by cutting off ".wav"
            String cleanName = selectedTrack.replace(".wav", "");

            // Update the UI via our controller reference
            if (activeController != null) {
                activeController.updateSongLabel(cleanName);
            }

        } catch (Exception e) {
            System.out.println("Jukebox failed to cycle track.");
            e.printStackTrace();
        }
    }

    public static void stopMenuMusic() {
        if (menuPlayer != null) {
            menuPlayer.stop();
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}