package application;

public enum MascotAnimationState {
    IDLE, READY, PITCH_WINDUP, PITCH_RELEASE, BATTING_PREP, SWING_ANTICIPATION,
    CONTACT, FOLLOW_THROUGH, RUNNING, SLIDING, FIELDING, CATCHING, THROWING,
    SAFE_CELEBRATION, HOME_RUN_CELEBRATION, TEAM_CELEBRATION,
    STRIKEOUT_REACTION, LOSING_REACTION, VICTORY,
    SURPRISED, DETERMINED, HAPPY, ANGRY, TIRED
}
